apiVersion: v1
kind: Service
metadata:
  name: qwen3-4b-instruct-vllm
  namespace: llm
spec:
  selector:
    app: qwen3-4b-instruct-vllm
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP